### PR TITLE
Improve app selected view

### PR DESCRIPTION
**Pull request by 10xLaCroixDrinker**
@mmoulton here is a left nav type view for selecting a deployment. what do you think?

cc: @kennedyj @sukrit007 

screen shot 2015-09-15 at 8 37 36 am

### CODE REVIEW

**Comment by sukrit007** [comment]
I like this view better :)

Wondering, if we should also show git commit information (first 5 characters)  (if available)  in list view and full commit info in right view.

I always end up going to diagnostic tab everytime to get that information,  wondering that should be easily available in summary view. 

@mmoulton  @kennedyj   @jking90  thoughts ?   If needed we can do a separate ticket for same.

**Comment by 10xLaCroixDrinker** [comment]
- Made sidenav toggleable
- Moved action buttons into FAB in toolbar (including new toggle sidenav button)
- Moved tabs to bottom of screen
- Change deployment ID in sidenav to commit SHA
- changed raw status on both sidenav and header to provide humanized status with timing
- added commit link to header
- made rows in hosts table no longer clickable, added 'go' buttons
- removed button from top toolbar that didn't do anything

### New app selected view

screen shot 2015-09-15 at 12 24 06 pm

### FAB open

screen shot 2015-09-15 at 12 24 17 pm

### Sidenav open

screen shot 2015-09-15 at 12 24 35 pm

@mmoulton @kennedyj @sukrit007 

> Note this has some non production ready stuff in it that needs #29 to be merged in order to be ready.

**Comment by 10xLaCroixDrinker** [comment]
@mmoulton @kennedyj @sukrit007 

FAB when viewing running deployment:
screen shot 2015-09-16 at 2 31 23 pm

FAB when viewing decommissioned deployment (on logs view)
screen shot 2015-09-16 at 2 33 47 pm

I think this is ready to be merged. Let me know what you all think of the state of the app selected view here

**Comment by 10xLaCroixDrinker** [comment]
Made follow logs button sibling to FAB (only visible on logs view)
screen shot 2015-09-17 at 7 58 09 am

Open FAB on logs view of promoted deployment
screen shot 2015-09-17 at 7 58 18 am

Open FAB on summary view of decommissioned deployment
screen shot 2015-09-17 at 7 58 39 am

**Comment by sukrit007** [comment]
@jking90   I am consistently getting app hanging due to transition. It causes CPU utilization to go really high.  This happens when I change deployment in deployment view.

Also the last state shown seems incorrect for the old deployments. It says stopped instead of decommissioned.

Also can we change cursor for "totem"  home link to hand ?

**Comment by sukrit007** [comment]
Also I miss the state info (and when it got promoted/failed) in the deployment summary view.  Now I have to go to version list or diagnostic info to view the final state.

**Comment by kennedyj** [comment]
Regarding the state verbiage change, this was a change that got discussed, and while promoted and decommissioned are the state names totem itself uses, they don't bring along the desired human meaning with them.

Up, and stopped convey the meaning in a non-technical way, while still giving the correct state information.

**Comment by sukrit007** [comment]
How about "deleted"?     I agree decommissioned can be confusing, but we also end up removing the deployment. For someone troubleshooting issue this might get confusing.  Just my 2 cents.

**Comment by 10xLaCroixDrinker** [comment]
:+1:  for deleted

**Comment by 10xLaCroixDrinker** [comment]
@sukrit007 I changed the cursor over totem to a pointer, changed the wording from 'stopped' to 'deleted' and I added the current state/timing to the right side of the toolbar.

Neither @kennedyj nor I were able to reproduce your hanging issue.

**Pull request merged**
