### PR TITLE
App view enhancements

### PR DESCRIPTION
**Pull request by kennedyj**
Overhauled the application list and view. Includes performance enhancements to cut down load times. Also added hotkey support, a progress bar, and other styling tweaks.

### CODE REVIEW

**Comment by sukrit007** [comment]
**Improvement**:
@kennedyj  Looks super cool.  The only feature I miss the most was having ability to look at status without having a need to select the branch. Please find before and after comparison:
**Before**:
before

**After**:
after

**Comment by sukrit007** [comment]
**Clarification / Suggestion**:
I like the new events view, but miss following: 
- Time taken for validating deploy (Christian might weigh in as well on this)

In addition:
- How are we determining timing for pull ?  I do not emit event to capture that
- Term "run"  is slightly confusing.  (May be just to me)

events

**Comment by sukrit007** [comment]
**Issue**: totem demo is not showing how long it has been running.  I just observed it for one deployment.

totem-demo

Existing issue with deployment. Please ignore.

**Comment by sukrit007** [comment]
**Issue**
"..." button does not collapse all the buttons

collapse

**Comment by sukrit007** [comment]
**Issue**:

Unable to recover past deployments. The recover button is always grayed out.

recover

**Comment by kennedyj** [comment]
As discussed, the FAB issue isn't going to be resolved for now, and the status and last deploy time for each branch is going to go into a separate feature branch.

**Comment by sukrit007** [comment]
@kennedyj  I am able to restore deployment. However , after restore events view get messed up. ( I am assuming that it is current limitation)

Before:
before-recover

After:
after-recover

Let me know and we can mark it as current limitation and I can accept the PR.

 Added new issue: https://github.com/totem/dashboard-v2/issues/37.

**Pull request merged**
