### PR TITLE
Better hosts view

### PR DESCRIPTION
**Pull request by 10xLaCroixDrinker**
This improves the list of hosts on the selected application view
screen shot 2015-08-17 at 10 24 18 am

### CODE REVIEW

**Comment by sukrit007** [comment]
Lets get the aggregated feedback from others as well, but here is my **opinion**:
- I like that it is now capturing all the info I needed even for special cases like orchestrator.
- Probably would like tabulated listing in favor of drop-down selection for hosts.
- Upstream listing might be confusing.  Probably once we have URL links it might make more sense.
- Not sure if we need explicit unit name (Unit 1, Unit 2....)  as we already have unit service name (myapp@1.service, myapp@2.service). If we do think that is important, currently, it only lists "Unit 1" . We might be able to extract the number from the unit service names.

**Comment by mmoulton** [comment]
I concur with everything @sukrit007 said, plus:

There is no date / time info anywhere on the page. I want to know when it was promoted / decommissioned / etc. This might best be done by handling the list of items in the dropdown next to the branch name better. I can envision this data being represented in a left or right column (nav) that had the state and some timing info. Here is a ANSII example of what I'm thinking:

```
---------------------------------------------
| Running - now
---------------------------------------------
| Failed - 2 min ago
---------------------------------------------
|  Promoted - 7 min ago
---------------------------------------------
|  Decommissioned -  7 min ago
---------------------------------------------
|  Failed - 3 days ago
---------------------------------------------
```

With the above being the case, we can move the container name (totem-develop-us-west-1-totem-totem-demo-develop-1439593099372) to a metadata section that included the image name and any other relevant info.

**Comment by 10xLaCroixDrinker** [comment]
@sukrit007 What do you think of this?

@mmoulton We've made #11 to implement your feedback

screen shot 2015-08-21 at 7 24 27 am

**Comment by mmoulton** [comment]
Thanks @jking90 @sukrit007 for #11, I'll add an example soon.

For this change, this looks good @jking90. If you want, I don't think the hosts need to be form elements. There is no actual functionality associated with them. Correct @sukrit007?

**Comment by 10xLaCroixDrinker** [comment]
@mmoulton The selected host determines where the link button on the locations go

**Comment by sukrit007** [comment]
@jking90  Looks good.  

@jking90  @mmoulton  @kennedyj  Thoughts on tabulated representation for hosts  ?  

| Hostname | Path | Port | Actions |
| --- | --- | --- | --- |
| orchestrator.r53.us-west-1.th.melt.sh | / | 9400 | [Lock Button]   [Link] |
| orchestrator.r53.us-west-1.th.melt.sh | /dummy | 9400 | [Lock Button]   [Link] |
| orchestrator.elb.us-west-1.th.melt.sh | /external | 9400 | [Lock Button]   [Link] |

**Comment by mmoulton** [comment]
I think a table view makes the most sense.

**Comment by 10xLaCroixDrinker** [comment]
@sukrit007 @mmoulton I implemented the tabulated host/location data. The 'go' button was removed, because clicking the row will open it in a new window.

screen shot 2015-08-21 at 11 13 28 am

**Comment by mmoulton** [comment]
Nice. I'm good with a merge at any point.

**Pull request merged**
