### PR TITLE
Working clone button

### LINKED ISSUE #26: Ability to activate previous deployed version
As  a totem user, I need the ability to rollback to previous deployed version in scenarios where current version of application is not stable.

AC
- Re-activate button should only be shown applications that are in: DECOMMISSIONED, FAILED states

API Call:
TBD:   Need to fix state management API call for a deployment. Though posting ful job information achieves the same, but will fix this API and update this ticket.

### PR DESCRIPTION
**Pull request by 10xLaCroixDrinker**
fixes #26

### CODE REVIEW

**Comment by sukrit007** [comment]
@jking90  Since it is no longer clone, can we  rename this button to "Activate"

Also , after  activating old versions, events view is no longer correct. If needed I can create a separate issue as it does not seem related to activate functionality.

**Comment by 10xLaCroixDrinker** [comment]
@sukrit007 how do you feel about calling it "restore"?

**Comment by sukrit007** [comment]
:+1:   for restore .   Will create separate ticket for events view.

**Comment by 10xLaCroixDrinker** [comment]
@sukrit007 implemented new name "restore"

**Pull request merged**
